### PR TITLE
Updated to 1.3.9 Beta

### PR DESCRIPTION
**Pull request by Mizzion**
I have updated this to work with the  latest beta 1.3.9

### CODE REVIEW

**Comment by Pathoschild** [comment]
These changes are included in the newer [pull request #4](https://github.com/bmarquismarkail/SV_PotC/pull/4), so it's safe to close this one.

**Comment by Pathoschild** [comment]
@Mizzion Can you close this pull request to avoid confusion, since it's included in #5?

**Comment by Mizzion** [comment]
Done

**Comment by Pathoschild** [comment]
Thanks!

**Pull request closed without merging**
